name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Install Dependencies
      run: npm install
    - name: Build for Windows
      run: npm run build -- --platform=win32 --arch=x64
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: out/make/*.exe

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x64, arm64]
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Install Dependencies
      run: npm install
    - name: Build for macOS (${{ matrix.arch }})
      run: npm run make -- --platform=darwin --arch=${{ matrix.arch }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-${{ matrix.arch }}-build
        path: out/make/*.zip
