name: AutoBuild  # 工作流的名称

permissions:
  contents: write  # 给予写入仓库内容的权限

on:
  push

jobs:
  release:
    name: build and release electron app  # 任务名称
    runs-on: ${{ matrix.os }}  # 在matrix.os定义的操作系统上运行

    
    strategy:
      fail-fast: false  # 如果一个任务失败,其他任务继续运行
      matrix:
        os: [windows-latest, macos-latest]  # 在Windows和macOS上运行任务

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4  # 检出代码仓库

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.0  # 安装Node.js 18.19.0 （这里node环境是能够运行代码的环境）

      - name: Install Dependencies
        run: |
          npm i -g pnpm
          pnpm install  # 安装项目依赖

     
